import { Category } from './app/shared/models/Category'
import {Recipe} from './app/shared/models/Recipe'
import { Icon } from './app/shared/models/Icon'

export const sample_recipes: Recipe[] = [
    {id: '1',
    name: 'Mince meat w/vegetables',
    imageUrl: '/assets/images/recipes/mince_meat.jpg',
    steps: ["cook"],
    categories: ["Main", "Beef"],
    },
    {id: '2',
    name: 'Traditional Carbonara',
    imageUrl: '/assets/images/recipes/carbonara.jpg',
    steps: ["cook"],
    categories: ["Main"],
    },
    {id: '3',
    name: 'BBQ Chicken',
    imageUrl: '/assets/images/recipes/chickenbbq.jpg',
    steps: ["cook"],
    categories: ["Main", "Chicken"],
    },
    {id: '4',
    name: 'Chicken Burrito',
    imageUrl: '/assets/images/recipes/burrito1.jpeg',
    steps: ["cook"],
    categories: ["Main", "Burritos", "Chicken"],
    },
    {id: '5',
    name: 'Apple Turnovers',
    imageUrl: '/assets/images/recipes/apple_turnovers.jpeg',
    steps: ["cook"],
    categories: ["Dessert"],
    },   
    {id: '6',
    name: 'Breakfast Burrito',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Breakfast", "Burritos"],
    }, 
    {id: '7',
    name: 'Frango à brás',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Main", "Chicken"],
    },
    {id: '8',
    name: 'Salada Russa',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Sides", "Main", "Salads"],
    },
    {id: '9',
    name: 'Carne de porco à Portuguesa',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Main"],
    },
    {id: '10',
    name: 'Airfryer brocolli',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Sides"],
    },
    {id: '11',
    name: 'Airfryer Carrots',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Sides"],
    },
    {id: '12',
    name: 'Airfryer fries',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Sides"],
    },
    {id: '13',
    name: 'Beef Burguer',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Main"],
    },
    {id: '14',
    name: 'Popcorn chicken',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Main"],
    },
    {id: '15',
    name: 'Semifrio gelatina',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Dessert"],
    },
    {id: '16',
    name: 'Baba de camelo',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Dessert"],
    },
    {id: '17',
    name: 'Brigadeiros',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Dessert"],
    },
    {id: '18',
    name: 'Apple&Cinnamon Overnight oats',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Breakfast", "Oats"],
    },
    {id: '20',
    name: 'Strawberrie&Banana Smoothie',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Breakfast", "Smoothies"],
    },
    {id: '21',
    name: 'Yogurt bowl',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Breakfast"],
    },
    {id: '22',
    name: 'P&B Sandwich',
    imageUrl: '',
    steps: ["cook"],
    categories: ["Breakfast", "Sandwhiches"],
    },
]

export const main_Categories: Category[] = [
    {id: '1', 
    name:"Main", 
    path:"main-recipes",
    imageUrl:'/assets/images/categories/lunch.jpg',
    description: "Welcome to my lunchtime haven, where flavor meets convenience and creativity knows no bounds! Dive into a diverse array of "+
    "lunch recipes featuring succulent chicken, hearty beef, savory pork, and more. Whether you're craving the sizzle of a juicy burger, "+
    "the comfort of a classic burrito, or the timeless appeal of a hotdog, our lunch recipes have you covered. Indulge in the richness of traditional "+
    "dishes from around the globe, from Italian carbonara and pasta delights to fragrant rice bowls bursting with international flavors. "+
    "Elevate your midday meal with our tantalizing lunch recipes that are sure to satisfy your hunger and ignite your culinary imagination.",
    },
    {id: '2', 
    name:"Breakfast", 
    path:"breakfast-recipes",
    imageUrl:'/assets/images/categories/breakfast.jpeg',
    description: "-",
    },
    {id: '3', 
    name:"Dessert", 
    path:"dessert-recipes",
    imageUrl:'/assets/images/categories/dessert.jpg',
    description: "-"},
    {id: '4', 
    name:"Sides", 
    path:"sides-recipes",
    imageUrl:'/assets/images/categories/sides.jpeg',
    description: "-",
    }
]


export const sub_categories_Main: Category[] = [
    {id: '5', 
    name:"Beef",
    path:"beef", 
    imageUrl:'',
    description: "Beef",
    parent_category: "Main",
    },
    {id: '6', 
    name:"Chicken", 
    path:"chicken",
    imageUrl:'',
    description: "Chicken",
    parent_category: "Main",
    },
    {id: '7', 
    name:"Burritos",
    path:"burritos", 
    imageUrl:'',
    description: 
    "Discover the delightful world of burritos! From classic Mexican-style burritos bursting with seasoned meats, "+ 
    "beans, and cheese, to inventive fusion creations featuring bold flavors from around the globe, my burrito " +
    "recipes are sure to satisfy your cravings. Whether you prefer them stuffed with tender grilled chicken or veggies, "+
    "whether you want it for lunch or breakfast there's a burrito recipe here for you",
    parent_category: "Main",
    }

]


export const sub_categories_Breakfast: Category[] = [
    {id: '8', 
    name:"Oats", 
    path:"oats",
    imageUrl:'',
    description: "Oats",
    parent_category: "Breakfast",
    },
    {id: '10', 
    name:"Smoothies", 
    path:"smoothies",
    imageUrl:'',
    description: "smoothie",
    parent_category: "Breakfast",
    },
    {id: '11', 
    name:"Sandwhiches", 
    path:"sandwhich",
    imageUrl:'',
    description: "sandwhich",
    parent_category: "Breakfast",
    }
]


export const sub_categories_Dessert: Category[] = [
    {id: '9', 
    name:"Cake", 
    path:"cake",
    imageUrl:'-',
    description: "cake",
    parent_category: "Dessert",
    }
]

export const sub_categories_Sides: Category[] = [
    {id: '12', 
    name:"Salads", 
    path:"salad",
    imageUrl:'-',
    description: "salad",
    parent_category: "Sides",
    }
]

export const sample_categories: Category[] = main_Categories.concat(sub_categories_Main ,sub_categories_Breakfast, sub_categories_Dessert, sub_categories_Sides);

export const sample_icons: Icon[] = [
    {id: '1', 
    name:"Instagram", 
    imageUrl:'/assets/images/icons/instagram.ico',
    router: 'https://www.instagram.com/xicocorreia17/'
    },
    {id: '2', 
    name:"Twitter", 
    imageUrl:'/assets/images/icons/twitter.ico',
    router: 'https://twitter.com/XicoCorreia17'
    },
    {id: '3', 
    name:"Facebook", 
    imageUrl:'/assets/images/icons/facebook.ico',
    router: 'https://www.facebook.com/francisco.correia.39/'
    },
    {id: '4', 
    name:"LinkedIn", 
    imageUrl:'/assets/images/icons/linkedin.ico',
    router: 'https://www.linkedin.com/in/francisco-correia7/'
    },
    {id: '5', 
    name:"Github", 
    imageUrl:'/assets/images/icons/github.ico',
    router: 'https://github.com/XicoCorreia'
    }
] 